source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'icalia-sdk-core', path: '../core'

# Specify your gem's dependencies in icalia-sdk-event-webhook.gemspec
gemspec
