services:
  core:
    image: icalialabs/icalia-sdk-ruby${TESTING_IMAGE_TAG:-:testing-latest}
    command: bundle exec rake spec

  event_notification:
    image: icalialabs/icalia-sdk-ruby${TESTING_IMAGE_TAG:-:testing-latest}
    command: bundle exec rake spec
  
  event_webhook:
    image: icalialabs/icalia-sdk-ruby${TESTING_IMAGE_TAG:-:testing-latest}
    command: bundle exec rake spec
  
  event_meta:
    image: icalialabs/icalia-sdk-ruby${TESTING_IMAGE_TAG:-:testing-latest}
    command: bundle exec rake spec
  
  sdk_meta:
    image: icalialabs/icalia-sdk-ruby${TESTING_IMAGE_TAG:-:testing-latest}
    command: bundle exec rake spec
