services:
  build_base: &build
    image: icalialabs/icalia-sdk-ruby${TESTING_IMAGE_TAG:-:testing-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USERNAME: ${USER:-you}
    volumes:
      - type: bind
        source: .
        target: /workspaces/icalia-sdk
    
    stdin_open: true
    tty: true

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # entrypoint: /workspaces/icalia-sdk/bin/dev-entrypoint.sh

    command: bundle exec rake build

    environment:
      # Use the local pubsub emulator instead of Google Cloud:
      PUBSUB_EMULATOR_HOST: pubsub:8085

  core_build: &core
    <<: *build
    working_dir: /workspaces/icalia-sdk/core

  core_tests:
    <<: *core
    command: bundle exec rake spec

  event_notification_build: &event_notification
    <<: *build
    working_dir: /workspaces/icalia-sdk/event-notification

  event_notification_tests:
    <<: *event_notification
    command: bundle exec rake spec
    depends_on:
      - pubsub

  event_webhook_build: &event_webhook
    <<: *build
    working_dir: /workspaces/icalia-sdk/event-webhook
  
  event_webhook_tests:
    <<: *event_webhook
    command: bundle exec rake spec

  event_meta_build: &event_meta
    <<: *build
    working_dir: /workspaces/icalia-sdk/event
  
  event_meta_tests:
    <<: *event_meta
    command: bundle exec rake spec
    depends_on:
      - pubsub

  sdk_meta_build: &sdk_meta
    <<: *build
    working_dir: /workspaces/icalia-sdk/sdk
  
  sdk_meta_tests:
    <<: *sdk_meta
    command: bundle exec rake spec
    depends_on:
      - pubsub
