version: '3.7'

services:
  libraries: &library
    image: icalialabs/icalia-sdk-ruby:development
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src
    entrypoint: /usr/src/bin/dev-entrypoint.sh

  core:
    <<: *library
    working_dir: /usr/src/core

  event_notification:
    <<: *library
    depends_on:
      - pubsub
    working_dir: /usr/src/event-notification
  
  event_webhook:
    <<: *library
    working_dir: /usr/src/event-webhook
  
  event_meta:
    <<: *library
    depends_on:
      - pubsub
    working_dir: /usr/src/event
  
  sdk_meta:
    <<: *library
    depends_on:
      - pubsub
    working_dir: /usr/src/sdk
