version: '3.7'

services:
  libraries: &library
    image: icalialabs/icalia-sdk-ruby:development
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    entrypoint: /usr/src/bin/dev-entrypoint.sh

  event_core:
    <<: *library
    working_dir: /usr/src/gems/icalia-sdk-event-core

  event_notification:
    <<: *library
    working_dir: /usr/src/gems/icalia-sdk-event-notification
  
  event_webhook:
    <<: *library
    working_dir: /usr/src/gems/icalia-sdk-event-webhook
  
  event_meta:
    <<: *library
    working_dir: /usr/src/gems/icalia-sdk-event
  
  sdk_meta:
    <<: *library
    working_dir: /usr/src/gems/icalia-sdk