version: '3.7'

services:
  # Emulates AWS SNS and SQS - see https://github.com/p4tin/goaws
  goaws:
    image: pafortin/goaws
    ports:
      - ${ICALIA_SDK_SNS_PORT:-4100}:4100
    volumes: [ './goaws-config.yaml:/conf/goaws.yaml' ]
    networks:
      backend:
        aliases:
          - sqs.goaws
          - sns.goaws
          - sqs.us-west-2.goaws
          - sns.us-west-2.goaws
