version: '3.7'

services:
  libraries: &library
    image: icalialabs/icalia-sdk-ruby:development
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src
    entrypoint: /usr/src/bin/dev-entrypoint.sh

  core:
    <<: *library
    working_dir: /usr/src/gems/core

  event_notification:
    <<: *library
    depends_on:
      - pubsub
    working_dir: /usr/src/gems/event-notification
  
  event_webhook:
    <<: *library
    working_dir: /usr/src/gems/event-webhook
  
  event:
    <<: *library
    depends_on:
      - pubsub
    working_dir: /usr/src/gems/event
  
  sdk:
    <<: *library
    depends_on:
      - pubsub
    working_dir: /usr/src/gems/sdk
