Local:                              # Environment name that can be passed on the command line
                                    #     (i.e.: ./goaws [Local | Dev]  -- defaults to 'Local')
  Host: goaws                       # hostname of the goaws system  (for docker-compose this is the tag name of the container)

  # you can now use either 1 port for both sns and sqs or alternatively you can
  # comment out Port and use SqsPort + SnsPort for compatibilty with yopa and
  # (fage-sns + face-sqs).  If both ways are in the config file on the one
  # "Port" will be used by GoAws:
  Port: 4100                        # port to listen on.
  # SqsPort: 9324                     # alterante Sqs Port
  # SnsPort: 9292                     # alternate Sns Port

  Region: us-west-2

  AccountId: "100010001000"

  LogMessages: true
  LogFile: ./goaws_messages.log  # Log filename (for message logging

  QueueAttributeDefaults:           # default attributes for all queues
    VisibilityTimeout: 30              # message visibility timeout
    ReceiveMessageWaitTimeSeconds: 0   # receive message max wait time

  Queues:                               # List of queues to create at startup
    - Name: artanis_development_default             # Queue name
      ReceiveMessageWaitTimeSeconds: 20 # Queue receive message max wait time
    - Name: artanis_development_icalia_events       # Queue name
      ReceiveMessageWaitTimeSeconds: 20 # Queue receive message max wait time
    
    - Name: vulcan_development_default 
      ReceiveMessageWaitTimeSeconds: 20
    - Name: vulcan_development_icalia_events
      ReceiveMessageWaitTimeSeconds: 20
    
    - Name: cthulhu_development_default 
      ReceiveMessageWaitTimeSeconds: 20
    - Name: cthulhu_development_icalia_events
      ReceiveMessageWaitTimeSeconds: 20
  
  # List of topics to create at startup:
  Topics:
      # Topic name:
    - Name: icalialabs-oauth-access-token
      # List of Subscriptions to create for this topic:
      Subscriptions:
          # Queue name:
        - QueueName: vulcan_development_icalia_events
          # Raw message delivery (true/false)
          Raw: false
          # FilterPolicy: '{"foo": ["bar"]}' # Subscription's FilterPolicy, json object as a string
        
        - { QueueName: cthulhu_development_icalia_events, Raw: false }

    - Name: icalialabs-organization
      Subscriptions:
        - { QueueName: artanis_development_icalia_events, Raw: false }
        - { QueueName: vulcan_development_icalia_events,  Raw: false }
        - { QueueName: cthulhu_development_icalia_events, Raw: false }

    - Name: icalialabs-membership
      Subscriptions:
        - { QueueName: artanis_development_icalia_events, Raw: false }
        - { QueueName: vulcan_development_icalia_events,  Raw: false }
        - { QueueName: cthulhu_development_icalia_events, Raw: false }

    - Name: icalialabs-cloud-identity
    - Name: icalialabs-code-repository

    - Name: icalialabs-code-check-run
    - Name: icalialabs-code-check-run-annotation
