$LOAD_PATH.unshift File.expand_path('./lib', __dir__)

require 'rspec/core/rake_task'
require 'icalia-sdk-event-webhook/version'

RSpec::Core::RakeTask.new(:spec)

task default: :spec

desc "Build icalia-sdk-event-webhook-#{Icalia::SDK::EVENT_WEBHOOK_VERSION}.gem"
task :build do
  system 'gem build icalia-sdk-event-webhook.gemspec'
end

desc "Build and push icalia-sdk-event-webhook-#{Icalia::SDK::EVENT_WEBHOOK_VERSION}.gem"
task release: :build do
  system "gem push icalia-sdk-event-webhook-#{Icalia::SDK::EVENT_WEBHOOK_VERSION}.gem"
end
