source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in icalia-sdk-core.gemspec
gemspec

gem 'byebug', '~> 11.1', '>= 11.1.1'
gem 'pry', '~> 0.12.2'
