$LOAD_PATH.unshift File.expand_path('./lib', __dir__)

require 'rspec/core/rake_task'
require 'icalia-sdk/version'

RSpec::Core::RakeTask.new(:spec)

task default: :spec

desc "Build icalia-sdk-#{Icalia::SDK::META_VERSION}.gem"
task :build do
  system 'gem build icalia-sdk.gemspec'
end

desc "Build and push icalia-sdk-#{Icalia::SDK::META_VERSION}.gem"
task release: :build do
  system "gem push icalia-sdk-#{Icalia::SDK::META_VERSION}.gem"
end
