name: CI & CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_test_image:
    name: Build Test Image
    runs-on: ubuntu-latest
    outputs:
      build-uuid: ${{ steps.uuidgen.outputs.uuid }}
      build-runner-uid: ${{ steps.variables.outputs.runner-uid }}
      build-runner-user: ${{ steps.variables.outputs.runner-user }}
      build-timestamp: ${{ steps.build-timestamp.outputs.timestamp }}

      git-branch: ${{ steps.variables.outputs.git-branch }}
      git-dasherized-branch: ${{ steps.variables.outputs.git-dasherized-branch }}

      git-commit-sha: ${{ steps.variables.outputs.git-commit-sha }}
      git-commit-short-sha: ${{ steps.variables.outputs.git-commit-short-sha }}

    steps:
      - # We'll generate a unique id that we'll use to identify the build run
        # on our systems
        name: Generate UUID for build
        id: uuidgen
        run: echo "::set-output name=uuid::$(uuidgen)"

      - name: Set additional variables
        id: variables
        uses: icalia-actions/common-variables@v0.0.3

      - name: Set build timestamp
        id: build-timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        id: build_test_image
        uses: docker/build-push-action@v2
        with:
          target: development
          platforms: linux/amd64

          builder: ${{ steps.buildx.outputs.name }}

          build-args: |
            DEVELOPER_UID=${{ steps.variables.outputs.runner-uid }}
            DEVELOPER_USERNAME=${{ steps.variables.outputs.runner-user }}
          tags: |
            icalialabs/icalia-sdk-ruby:testing-${{ steps.variables.outputs.git-dasherized-branch }}
            icalialabs/icalia-sdk-ruby:testing-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  run_core_tests:
    name: Core
    uses: IcaliaLabs/icalia-sdk-ruby/.github/workflows/run-tests.yml@122176019d357a02c9f3631243eb440dc996948f
    needs:
      - build_test_image
    with:
      build-runner-uid: ${{ needs.build_test_image.outputs.build-runner-uid }}
      build-runner-user: ${{ needs.build_test_image.outputs.build-runner-user }}
      test-service-name: core_tests
      git-dasherized-branch: ${{ needs.build_test_image.outputs.git-dasherized-branch }}

  run_event_notification_tests:
    name: Event Notification
    uses: IcaliaLabs/icalia-sdk-ruby/.github/workflows/run-tests.yml@122176019d357a02c9f3631243eb440dc996948f
    needs:
      - build_test_image
    with:
      build-runner-uid: ${{ needs.build_test_image.outputs.build-runner-uid }}
      build-runner-user: ${{ needs.build_test_image.outputs.build-runner-user }}
      test-service-name: event_notification_tests
      git-dasherized-branch: ${{ needs.build_test_image.outputs.git-dasherized-branch }}

  run_event_webhook_tests:
    name: Event Webhook
    uses: IcaliaLabs/icalia-sdk-ruby/.github/workflows/run-tests.yml@122176019d357a02c9f3631243eb440dc996948f
    needs:
      - build_test_image
    with:
      build-runner-uid: ${{ needs.build_test_image.outputs.build-runner-uid }}
      build-runner-user: ${{ needs.build_test_image.outputs.build-runner-user }}
      test-service-name: event_webhook_tests
      git-dasherized-branch: ${{ needs.build_test_image.outputs.git-dasherized-branch }}

  run_event_meta_tests:
    name: Event Meta
    uses: IcaliaLabs/icalia-sdk-ruby/.github/workflows/run-tests.yml@122176019d357a02c9f3631243eb440dc996948f
    needs:
      - build_test_image
    with:
      build-runner-uid: ${{ needs.build_test_image.outputs.build-runner-uid }}
      build-runner-user: ${{ needs.build_test_image.outputs.build-runner-user }}
      test-service-name: event_meta_tests
      git-dasherized-branch: ${{ needs.build_test_image.outputs.git-dasherized-branch }}

  run_sdk_meta_tests:
    name: SDK Meta
    uses: IcaliaLabs/icalia-sdk-ruby/.github/workflows/run-tests.yml@122176019d357a02c9f3631243eb440dc996948f
    needs:
      - build_test_image
    with:
      build-runner-uid: ${{ needs.build_test_image.outputs.build-runner-uid }}
      build-runner-user: ${{ needs.build_test_image.outputs.build-runner-user }}
      test-service-name: sdk_meta_tests
      git-dasherized-branch: ${{ needs.build_test_image.outputs.git-dasherized-branch }}
