on:
  workflow_call:
    inputs:
      build-runner-uid:
        required: true
        type: string
      build-runner-user:
        required: true
        type: string
      test-service-name:
        required: true
        type: string
      git-dasherized-branch:
        required: true
        type: string

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Load Testing Image
        id: load_test_image
        uses: docker/build-push-action@v2
        with:
          load: true
          target: development
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            DEVELOPER_UID=${{ inputs.build-runner-uid }}
            DEVELOPER_USERNAME=${{ inputs.build-runner-user }}
          tags: |
            icalialabs/icalia-sdk-ruby:testing-${{ inputs.git-dasherized-branch }}
            icalialabs/icalia-sdk-ruby:testing-latest
          cache-from: type=gha

      - name: Checkout the code
        uses: actions/checkout@v2.4.0

      - name: Run tests
        env:
          UID: ${{ inputs.build-runner-uid }}
          USER: ${{ inputs.build-runner-user }}
          TESTING_IMAGE_TAG: ":testing-${{ inputs.git-dasherized-branch }}"
        run: docker compose -f docker-compose.yml -f ci-compose.yml run --rm ${{ inputs.test-service-name }} rake spec
